apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:KbUXeVybfDGz2ZsdeENBFki2CRhyBNUKWYh9wtmN,iv:QOANhMOhm1IQhE7wRaIUY19y8jZMAYx12gbJZ7k1gW4=,tag:nMNcWSW98Mz1Fs7i32R73w==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:Mxry2cEZ4K4cxNUgrR2iFjzMaVwxu8APILFOdmSn,iv:V7cY0OHT/6axnbCzHigbDVNCNhsIL9drxHKXWgs/kBM=,tag:RhJzwv7qPtrhLaXPEBH8Bw==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cXR4UWI4emplY2VyYWJh
        U1JoNUxXRmNUSjZIN1FYNzRwakhjQmRyZHpnCnpUZTVuNGQvT28wVHJUa2IzUU1o
        RVdIb2FjUWx1VGRZeWpCOTZETU1CQmsKLS0tIEVsdUNaSlJmSUxJZWFJYlUyRE5M
        SXlsQ0FWcE04L2NnU001ejlkREVrYmcKcLVXT0S+Ger8haKLymH5hqgUXOzTO4BM
        uxS6V+LW7FGWhmenn1rWIZk0ptXK8K73iFuvkVL1tPN7QSGgViVMaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T23:00:44Z"
  mac: ENC[AES256_GCM,data:p0fQIPk5Em+zQDOz/MipwPbv46fZkMagUHAcCx3R1X1MrD5kP7LtJ7w/8/K8y46MHZV9CUZOi8/rqQXql4/MS5O3b5wFVSzwW4nlZW0DTxj7uBhDW1nu8oIV8ep0RRjuQDiN4SDy4c/RCHGWTiHmi2xrEH/nvNW5X5NVoensujE=,iv:oyeShb8quSeD37f3CXReJHF76OIyx1fzxePqt79eRpM=,tag:p4keAsJEbNYRLjxKZEeitQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
