apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:nwei22mES4rOIAoBuykFav+ujbuOPfSj7fn6w/g/,iv:xAvyyMxEaNod1WeozZYoe4/MJTiETQtfVweE5FVNma4=,tag:qK1ofzo6hG/Xg+ghRJJFSA==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:rEgqpoccc0TIWlNuLXrRX/rFXxY3CI0Ro3kfB9Yq,iv:QkoaX2VUrW9TemIrFq+iy+o27/GtjBkGKKsraYZ/AKU=,tag:lTW5Jl7AefAdYUKBljgLcg==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ0Y1MmRHK3Zxdk1VK3A4
        OU5FYXFueDF4amlhYlBwSGJEY1h5SlBMMWlBClNidC9zdGNrUUx1anAzWmRubWk4
        Z0tuMmthaytBbEQ2d2t5STB3OXN0L0kKLS0tIHZEUjRyYThYaFI5Qk9rKzJnaDkr
        ak1hQXZFVHNWNlhGUmkybVNpWjQzeVUKyU0F05XmA8WGvW0zvx3sgtDrDKuDfUr7
        f1ylnA308xXtWNRiXD1Ip8mmhCXpapl9EffakNEIGm5mM8v5Dfuy5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T14:05:37Z"
  mac: ENC[AES256_GCM,data:2DZhhu2PrOe4XL78Vj5mZ8yjJ73MceIYEG5pQe5vOgVlCH7Nm4P2f+EjZTIJdl0jobL0sqKcvBq7V6zBdi9ntcIljMLVTYhrWKZKdj++W6h1O3NQB3OSBKouGkHBg2vW2u/CnVNFuL2bM0cfPlYC9qP+DdzpRAwwNjeOKVP024A=,iv:X/yanqZcUDHhY0OXUtFMjmg/Zm2F67lGdKZycolCFXM=,tag:FbGKQRPZynuOX9p5HchNfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
