apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
stringData:
  ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:ihYxQ6q6WbrThpBw/iwgXIURzjqXAw3Ct2yH3UHJPMkizikE0bvnWXXOw+YT8W8z+b4GwWY+agI=,iv:UmG7ifa8wja2laO1wdb+kfPbXn7bweszpAvu9x2xQiM=,tag:MEt6zjGqTG1x3Mfh4meKsw==,type:str]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:TW7t/+l5qI561yAFHxbdhRvdC33fG+9hIFCkvX9R,iv:ASsukZ+eHEmWg5VKXdvWdW0mnYIbiSHxpyKwO06B9Zs=,tag:KiTRlD8+1UFhBwmOcwPmmA==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:jvV9tjCqjC2rEYbghMdm6LOQMCUC8tSviAvCGcIi,iv:gdCf/GQ0FF25WflLKe8t7VS/JX9qsoizC1kYTd+qpl4=,tag:00wcD3NK04UhkMfmqgN8Vg==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydlhTQkNBY1RTTHp1K2Vn
        dWxPZ1IzMS84SWEza0tSbTVLM2dJS3hDdnlBCjF2NzJVWGlPYnpLN0ZmZzI2NVQy
        UGhxeG1GenBmZkdtakE1QVl2TUZScUkKLS0tIGVhZHRpQ1lwY3JRcDh4YUZqeEhW
        UzF6YWNPSjdpbTE3MHczaUxCczdSL0kKjnrBn8oBk5X92/95xPB0+p0cVmZexIJh
        xwW57EgWWtuyzr2IeMhC2oAmsR9NbIfUWnxdEOj+0yLJCnoi5sIQcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T17:09:08Z"
  mac: ENC[AES256_GCM,data:1RMZL88I8ErARhu+nzCOTueOUhcCtzAB2KAB9DfW4naJFwKmiFkE/SKJByK9mjsqMM2EzFe1uzzegrxd3TKLimmiGGEtSNnB6lNcuTMiyZd5KReXnZjC9/LOb2GiAIqz+q6b3N8Iowp+7JsumApF4wmw+bq5BbKYSaZIXRk4sps=,iv:IPbm7zbK2nd9mZO+mfKmW/40j7KGHh73pQvNfTPD890=,tag:F8DQk1fzH4pH2qU3A33Baw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
