apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sBxJQH4RXxdvKrxZ+542NGep49bW5CgOrS6BH7WWQVZs6m8wx3DX2A==,iv:Hv5tI0HeToHMgwdIsbG7ijOP3SHYqazwG363dJmu0WQ=,tag:03Rjs/RBMBPZfNT8D0h5Xg==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUU5WbFpqRHJtM3JuMUlr
        V1hZcXZkWFRHQlhxd1RJK3A0TXJEZ1hHcGw0CmNzZ0h2by9WYzhldzFxZ0dWbUdU
        UDQ2Qkw1cXJ2OCtsdHhqV1NSY0JYVzAKLS0tIEVRNmhYclZpZXBxUXpwUzFrYzlX
        MkZlNFdBMjUva2hNWVFHSDlia1gxUTQKm2i0EP0CNH1GBIJuzesJWueRKiid8jk+
        0ha6A8U/zSK1Bl5+xyR+hIMHsYfO8MyrBoN1ic5x0B+HnLxK8CNCAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T17:09:33Z"
  mac: ENC[AES256_GCM,data:GI89i2tymW7satgeVFf7O8ZJ4bdxPT2LzkhiQfFlkdO9IspmuONhYUOpDnmMTmcoN7rH/ROUH06mxbgHxDH2wiTo/9Sk7Pypq/AfEeY+CRM0Q4oSkvE+OFl2kvpNEoovWHgzpJRFDUmqXmRru0RT6kD0LypE+ywFBy4F7sURD0M=,iv:+RY80FtI8NGqXTs/FQIiZFwAltDqfMTG+yIkUys/PAs=,tag:iRVFeVkP9Z2S9C9iu/Kdhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
