apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UylRw0HcIs4t8nZqe09vv+D0klsxwjhORhx+wOlqUJvXesWvEaOYiA==,iv:Dtd97NaoXCWEEAVlX4KhYoat167jY640Yo0zLwHL8hc=,tag:bhNRw1va0g9vbWC6NhpI7Q==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Unl4RnpGWkRYNVBLT091
        emxZN0R6Q2lpM2NKVVFIczUramVKY3FybGhNCmpISEd3eVlmUUhyWE9reWswSld6
        MFFtOXBtSzJKeTAvRkFldHFhQ2ZpZ1EKLS0tIGExQVgvMDJEY0hQSFhZM1pnclRR
        dTZnZDZ4czhXMDNCUksrZkp3WEVYM28KyxQBcwFF/1XpS6vQnz8PDYjhUnyptlB7
        l79ZEzncucm1yZ1lMNK5ETFMTPLPzI//BahBv3KkSWCvS/6l1oSBFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:44:10Z"
  mac: ENC[AES256_GCM,data:wy0NcA8FQTl5NE2QmcSPYLAgVBO+xx3kbQDspzfvkDSAb4KZD5boMX/OlyMaLlmtqTnL9W6wkTFbhHLjRa3HIelRavNdgneUWfn7Q1J1P07ykDad8H8PcN4FDCQtJWLbnJvnUAljZXoQmAcFnj4zT/XamWx+wQqc1UXT7RnwAEI=,iv:TYwC2hrDYiCJIw3yghu5JOayA2vMJY0s9eW7N3FDutY=,tag:AM5GPo5OWJ11evHix32ZuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
