apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:CO/cGiXYUXmb9E5vIw/ggTlzEUNY2oBcuGM4QbmZTJpUG0RFy2VKaw==,iv:kKU/60W7orMxdU25nS0+ga5StnuyolZx/uNkqiAqyV0=,tag:Bs8uDz63dsAQeL6Q7eegJA==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydGtvamJVaU93UkUxa2s4
        VVlzOUE0OHZwdFR2QXpCcXFsa1oyenNoTWxjCnBoM1U4K2pwMjVrK1h3clBTUGRE
        MFBxSzk0b1BDVmxMaWRrRUtQbi9VN2sKLS0tIGRYSzJXZUpFa1YvT0ZkWkNHZ09j
        V1VnTHhXVFdmQS9FRWJNL3JlOTY4ejQKZ7pnmUpjH9wzMLEugngXPVhoWvu9rd9Q
        48p+g80zqzbxXWUwDaTYC+bg21XPdxNAHkfQKqUTSnw8051wfBvDpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:51:47Z"
  mac: ENC[AES256_GCM,data:YUafzEoUw4jmU2hTaA7P4R4h8HrD6ZBQMDDy+qA5T6IKhZTjAMkGJV/MTeX4LZfN0abEZt93GPGvPRXU0OKLbHEXFgUPls0J2oHwDMuMEwDI4RvRCtfaf6boMo0mpsOei8ExwtC0luE1K++sshKxkngkmRIW3+G3NmhiqjEBHEE=,iv:WGXCMM1NgLO/SKqm/G3lAluzAqOXKcZq2xDsnBGrZGw=,tag:yw6ol98f7gyeph9Xl5Wo5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
