apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:19+ubtG7Kla5JuuBBA==,iv:8QDeptXdRdMsvUdsS9LPawU1J3dIYuVvdIARfUPJEwE=,tag:QI9h2hCJdOMVFvccVbOvMA==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYlVjQ01DMDNkSWx4aGpu
        SnoyWkJmQ3dJemd4VVdub0lEdzU0UzkycFVvCmFaczA2QkIza04waFNZb29RNDhC
        ZU90enR3L1pFVi84NkQxbDhVd3J5OEkKLS0tIExQcGhaT1U3dmp2MCs2TG5zbzlS
        dElwd2VpRDNja2RPQVY1Wmp1UDJuTzAKVOnLNszpuIyRuYzM7d2UANlr3CmXiAJ5
        xWExpSe8K6P83SXV1yUhF0rRnJ0OG67pCzkNtVybvkiC8f6+po6/TQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:44:10Z"
  mac: ENC[AES256_GCM,data:cPaFs7dWO0+jaczaCF6FfyoPwnFZ1cqpc+ciVp6K7W8tpmZBqlxOc7nRElm4X6QVyUClNMGXjsvJHQBTjz2nSaCBTdBNU6lkJKolPqVt/ny1Qdn6eyZPSHSdERpNomIqbioLa6ubez5PqmCp8Pb2hrCVwAWj5NUok6L+bd7UM04=,iv:ZBQydqVx0A8OSFH1p7JwbJJh91ye6qaxwxOge4ExBmU=,tag:NCG7TI5c/hFhn0WCRntB4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
