apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SA2I/5t31O3E,iv:bR6vsK5L9OJ5T2UgBMOIXPQfuQj9ecG60iLPc8GF34o=,tag:0qeOWedoI6gWf5DfmrzS3A==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVFhoeVRwTS8yci84eFlq
        bHBySXBhaUJQR0FwaXhmOG9teVpRVUlmckJrCmZOa2F6VVhJcmVscDNiQjk2SFRE
        UFl3dzFSVUNsSktvV3hkVlJsekxRN3cKLS0tIHFrZmFNZ3JOTHMrc3VwdXc3c3pV
        QmpHNlMzU1M0SEhNSUkwL1VFbStRYkEKhtzEuI8GofPJNzDT56a8+InmwxFMk3u6
        SIeZWMnkUVIrDS+sJ6iIVfOjsUCFjOM8iabulu45nq9gMq9Mvj+afQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T17:09:33Z"
  mac: ENC[AES256_GCM,data:nBwwWJ6oi7xH7XmPnvOOqKKAaqqLNkfTov6y1CVb+ZKJFya5a+uVRQBvVy9ZflmBhwCzWosmX4L6cCXHARW22veNj2ZglFOGU+J7OSpfk7nvUoWS/gRArD+jejsNbJJ8tIrWHQeObUp3/zZIpbzdJ00zsbBpsViPvV4wfGBeUvw=,iv:hpsZFS4oDRcV96WI1fKCHT1NDkKOXwgYN3jRlIaaaRg=,tag:RuL5MsnJYbZi4bvTY0bkXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
