apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:d0vCwL3K3YYS,iv:s3470bf0JWIK6I5b0ZotfTVtEjv3hZNr8E/uL1FiQWE=,tag:uzfCCgKj9evNrACOYO8Fag==,type:str]
  SECRET_IP4: ENC[AES256_GCM,data:HA5byTL2wDYtgKTy,iv:VWE3+/wk943i7LM9BKqwHUWQBv7KmTSQXG2iGdB7P+k=,tag:c96zAGmaqE3MO2dX7KzEdA==,type:str]
  SECRET_IP6: ENC[AES256_GCM,data:T/JWIkuT1x8urSgQBKGKX6862iFAHq1kSax/QE1yBI0bRiLQ,iv:lV0qM1OP+sU2+0jE2DwtXKxSbrHoOLjCQFg6UnnrbYs=,tag:PtrWJ54/rkUOOKrVeCD+AA==,type:str]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:mHygECfxMTQ70gYyNsjLN3B7eFQ4ANy9NUv9/rU6,iv:33RJNNVHLlYXwRw5FQZ6DLsVnKcnX3jdqxTe7oEIG/U=,tag:jeMKB1oF6+7gxtFsEerXHQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:0ALD9IbQAed3WlJyGL5FHWvVpK8NCp5HEc4gd/hS,iv:vjHNkmJyF5i5pdgEeiqeQ99lrvXMdIfyOq6e2JU0zHY=,tag:0yJP8WJNBLNywSuE3U2OBQ==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydjIvU0tQL2k2VUlLK0xQ
        TjFWc3FPZUVwZkEvdmNucUNxVTExNExSZ25nCnA4NGUxRnA5ZlI4bXMyOFdhdk1G
        UmNnOXhnejMzMVpFVUZlUWkxRUp0ejQKLS0tIFNLNTJCRjhXZUdKTVZnWFl0NnE4
        OUhBNGh3dXU2ZXhFOVBzUVUvUm9yMUUKUZIIyQJt/smWELgVAQfCYpGEwPeaFtYN
        OdsslnzeA05+hQpMrBECeL0CHclMRFDwN7vqDWNHfuQb6v8epdo35Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T18:50:30Z"
  mac: ENC[AES256_GCM,data:PrtMlr1lFBoWP2hz3XcDtMAT0WGzKecGKIBLxp20wBEjKK5sEyMQta7UkDEJio2skmYqom/V0jO7ha6wjg4wvcurBV5T6Vn7lRu5wlMiljy0vlRajuwRTljuaXpIOlxYEzSPOaJ0SbBeUO/5NrY/dIapt0mhxedvUt8zgE05kDo=,iv:hlp7ahtT/UoNxyLZsNVhOGf9evQaTTHg6P3Rkzq0ONs=,tag:jBrdPsfXOY8VwcgvJuI/kA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
