apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:bQudzRnw305+,iv:4OwPSAkevaprXKdPgWQOM+RyGA5kaL6BXEhSOwzwRrQ=,tag:a4A5d9kWyyDBs8j8Al2ZWw==,type:str]
  SECRET_IP4: ENC[AES256_GCM,data:Jqk6h9XtkF7kBXWS,iv:6nIQmNaBbpTBYip8vGRbyS0DiRVd3hLzMkXLPE3EoPI=,tag:o2TZK3ZIM/RFkGqc+OHXng==,type:str]
  SECRET_IP6: ENC[AES256_GCM,data:UabuFmrqDJUHJtva/6RK+7qHYfvPq9CnfFWlahiBVsdkvtY6,iv:8EtoMF94w78+KHD+jG5eNKmn/4DnhJ19W5iK+irFvoQ=,tag:40qDKxOr6VzeqQgBGrY3sw==,type:str]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:QVaBvGf+Fk57956cmPzaTRl74+BdgQyE3w2ieSdS,iv:DszvZbG3FB+5LnpwI52LlaoO896+AwTTPansevELRIU=,tag:M0dzrwhV58kf7U7tUoJBXA==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:fIe77gk4LHXp3sAc9WdtO+IsiHzS1TNCaWoCzfXy,iv:3x7RKvRtqrNiHWK4Wgf6J/CJDBD6X3eC8BJf/gaHKPE=,tag:gsswrQtkSZ5hfF4KAaAnUQ==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcTl4emxadEFldG1Tb2tC
        NTgxVllubDBZdW9rdVo2c2N3S0cyZ1dBc0JBCnlxd3ZKN1F6bHI1MDR3Mi8wRWxa
        S2FnWjVwaGx4d093L0ttclMySlBMR3MKLS0tIEoxSE14SHRrek9LUEdwRjE2eDlD
        Y1A1VFdVbDJGWmdKRXhBZjlBMW1jZWcKBleViNllKvAz6PI7idbYBjxvhx35BnRq
        mQk/SiFouKnZ6nA9CRTQ9bBArpzM5I3yzB5CxaGCYQv+CnfJQe+NLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T13:36:18Z"
  mac: ENC[AES256_GCM,data:17yWQthOwVOi+GXDirARwVayo5W+STOgFSvCuQfwKrdDNbzd5AAz2lALN4V/65sB6hYTi7C2ydfedfu+Cdsv0AdPfD4wBicjU7gIcRH2UtQ61mxadHKrv2uLSK63XaDIDbq80YBiTu1PUBVdDZUUVGTpGTI/jX+kjTyg6DKiSns=,iv:ecCRh/znbPWEq0pnxDzH46tVJVUnYkW4iK83QP2TYyM=,tag:wy3Okwqx92zpKrMz4w4b+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
