apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UwDYoTqmZavo,iv:HgYKNEnPinhZNWt4zHqdb3P9j1787Z2OWOVa8xplfdQ=,tag:6lqnRaWRWu1HURXLd3aQCQ==,type:str]
  SECRET_IP4: ENC[AES256_GCM,data:iGb4mYFjUNrxHLSq,iv:vVMXE+AB96j/1UCVELJY+BdVtCCgLv3dP0Ayldz/wPk=,tag:wKoeu+7+1f4sDa0wLmx6RQ==,type:str]
  SECRET_IP6: ENC[AES256_GCM,data:BSTPJZPc5LCC10ExwRfZWRGM9KGZC2oZ72neattJYcdl2s8N,iv:f9l1+YW9TCxT3trF6ObEKv6mAxU1GLkV6vZHNi0DVeI=,tag:stJBx42I3/as+gSC04xfpQ==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UmZnbVd3VmJsM2krSVo1
        cGhHZkNYUzgyMG5ZS0VGSXFmNTFNYklMQVFJCnUvMFlXR0ZpcTltRXhTYjFXUzAr
        akNicjJ6enVleUMrcDhkYVJ3OENnQk0KLS0tIHhVMk83anFJTDB6ZmYzUjAwREN3
        L2UwUVhjMWdzaXJIcmIrOEY0MGphTlUKZH7tGw7oc/7NbjO1HVaSW1Ji60MNmrl2
        0CiBNRvCKyn4uVm32gMSWaqT3ofFwx46eEZvJQTO2BAPDAJAZn0U3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T13:52:10Z"
  mac: ENC[AES256_GCM,data:WyoGSudG2prQfPmLS/tcLMieyZwpenkhey4lQ6uqREff4Pl78neiU+ORGVxVMNu4lrn/TlQFimLu2cEgdmdMYtgYOqF+7ePH4NAvgyvfKSuOEgtuz4oZn7rwmcASXOIOQYCeWog3eTymTcqt9xVFz4BkHBz0sxbCtr7zeTEi0X4=,iv:oGTHNl+qYckDIHH4YAg76XzWETdNhV9/n5o/PLCLWB4=,tag:3wYCA66gPbC1wZsob8V4vQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
