apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nD0qftA1x/SOTkh03g==,iv:LaQY4QAjsyM8fG+8DBb348ZlTlOlPpyc3/Y4M21mAL0=,tag:aWKbH8neXU6Ey+YUuRmhYA==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc1VvUUw1Qkh3MzRwU0dK
        OTA2S2RTcGZRbzBJaDFqV1h3N21DTTZmdGs4CnRubXVRd2o5bVI1clFzOVFBaEps
        NEdDa0MwVmI4bnF4SFlZUERSQXd4TUEKLS0tIEVaM0s5SHFNMHE2dysvZUFZcW15
        WnhjSHBjcFZZKzRKQURsRWtsTHlmYzAKVGNmDrQri2YACDy61YZ0Tj8GlHrpQhVy
        peztJG9zDxZ+cwPEp+rzQCR2BxnWhECDSnReLzfM7vv3xJ320Ju7bQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:51:47Z"
  mac: ENC[AES256_GCM,data:5F7/N9+t1gQrmYinbgmxIFmUP5pMMwVlUNGHGXrHEYz4hOlyoV4zOzIQw6N/VXI0UtIxuRonHXilIiMu9Djgopq7NsBVPIFeHIabe5Kho482JH7sc9pMQUNVz1UEOHWYx1orP8eFYTyfkTnE8nbyElX/GmDIf+hkBCwdp2Il1GY=,iv:E8WQY5X2P/6IEzgSdOjgoCcsh+CJHxxXw6YchUO3p3A=,tag:bDb6K0e9FKwRO+jYTIjODQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
