apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wqzt/22H5P/mWVdQGvl57XRWVQbSt676rSpZWNpCNCI=,iv:s9DFqPkgiiA+Y2LZn/4uCHO3XxJA76ehviwR1SQXYGw=,tag:4CteE8N3e3Su/RNcnFGTtA==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbTRleUt4NTFCL3FWVncz
        dGtDY3piaWZyZTF3WG4wZlJ6VWlyUmZWOHcwClQ5S3U3emNJNWFNblNYMGtTMkVT
        UlRFRFNCeWsyQXNxbHRpTzJHTGl6MzQKLS0tIEJ4cWl6azBML3N2eDZBS01DUnpX
        akZ2TDVtZk1YYy9UMnNtRXdjUklQU2cKXnxEWbSsPvmA373464SnoDyfbJwzQPfa
        ibt8FrSOqthiCJ6ZiZW2U0PDFka7nuwgfnN4LZrHt/eEPybKEKCZJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T17:09:33Z"
  mac: ENC[AES256_GCM,data:EaK1nip2IPzoEhMSfQVnMz4xNrQWvi8s36k9zNJdUL+P8H8TyiJjsJTXrbIGEvXOjRD50pFSeWCg0vCrAj6vCVZg26v3m4tCJ1fN3CQ4ULcvQVOfsyyjkYollA/245uNOlnXQvrI7QMw/hDANiMtO/BfL/CFUUngPNUvm0jBaFg=,iv:Yujc4cnss/c0ra56VM5gmnhkpjZzakJMnexA36v5Hc0=,tag:z1OfS1mEieHFYJNRRYNQPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
