apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Wfdz6Pp0aEY1zb1v0fYcLak/WSJJg6q8q/pPAb6xLzY=,iv:kESOWR7KgDAKO8rCnQm7/JAItcBfLnhRc52Us0q/6ZA=,tag:eQmRmJiOjVfCK52kLCmXmw==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaWM3MC9RbmtpY0FqUzRs
        NmZpclc0RVN3U2lKaTF1WWpYYTR1dGZMVEFjCkdTKzc4RTU5eGZGRDcyWFI2eU5k
        UjJNRXZlWlBXclR0dFdldzhLS3JJV28KLS0tIGhEM0gxdnBKTkhMQjIreDFDcWZX
        Y3dZVE9HYnVvSWd0TWtCU2Q2ZC8yaWcKj1NieExHO4tNSTxsnR8Fr8BXzuxe5uq1
        KXeJOe/EkTOMmszWWyz9BxsIT1cn/aMe19TztpixE/wK5nRH/TF7Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:44:09Z"
  mac: ENC[AES256_GCM,data:rIivKWkvKTBzqcBszxyhNv//ymxwz2DpcqH5BBB/s65WYdfKE65uNCK8vbIT8Uv3DKjsGsLyeFPZk+N/KXwsDwoED81QB08f+ty6SgLujMl0C9Y+aFt4fVCnZEaGvUFBIlMkbDPFJhuo2nZN3rPIyuDKeE0AK8wKXGPdmp0ddIs=,iv:mBkpZlrFruNtA4FzHmV09QQ/yYBirDwJDm5WNqp7goc=,tag:HUBHWk95n6I6z+roeYaSDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
