apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:rl/NMO538fVY9AiEUKEjg4UifILUnXBbdT9pjAMlIfg=,iv:djnipmn3eMoFCUa8K4lCgVSUHYH73u3DAX4tlt6jz8E=,tag:6dciyYm3EEsdRxaD5WLoyg==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZVVYMnB0VERQdXZERDJE
        MlZ0MkFWZGpkRTFDVXRlWkZSdnZnU0V3NlQ0CjBZSTk1YUx1SXkrdTJYTWZSMVdP
        djlTdW9EcVJHWTkwc0p2ajcrTEJCVUkKLS0tIFordmhIem9EeTBHRkhlR2JKTDZH
        Q2FWNnNDRHZSZTFyWExERUdWNkZ6eUUKM1P39NMJUpKdRZeJZ6eUGJFt9bKYmcaJ
        EZPisAPOzmRazro595Zl8OVmexC2sLQGGdEW2YjBHiO8C1PtyyJcRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:51:47Z"
  mac: ENC[AES256_GCM,data:pnAMjXjGhRaa6OkTEGHhcBiP1pmcg1yTJyKPSUYZTFLR4glDXq9ZF5jqYp63pdchmF5HTIEHu/+zjLq/OPM4iOR6lgMmbRPFJGcqEK4DLErs+C+rY2A0wMA1Qistvsg1/pisrOreFQyhHKOxgHyy2Y3TzI6BdfJQQd7RFmiymA4=,iv:EEpHW/6jEejKuak6qfms1nMWKpuh31GtuhNdDnqLfM4=,tag:nb72N5UQejpS+iK/4Uuo2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
