apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:EXILYYCkOhsFH8x8FwRzEQ1BJ5lwjBMlfp/l9mt/qMV/PqyqKHDO/WNXAHjPV723HLm3DXY0wiJi/qIew6o=,iv:9RdR0wdeW/svKZVRIo9xhM4Ctb42GSm1XodVtFD6b/Q=,tag:GPTj0NKvrYuk7t7JtbsnzQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV0VtU29oK2xVNExablhY
        RWsvQkhMUFZMeEYvWGJTUFRxaU1KQ2FNZFFRCnk3U2xhZmErN3BqeklELzNjOE52
        WWdjUFM1WCtLS2xRSWxVMjFPMXhkdW8KLS0tIDZ2c2dSVTFJdU50TlhIRC9vd2ph
        K1Rreld3ZTF3MUpwTUVERFNNYXJiUUkKsl8iLY0jq0wTyw5daVPDq/sW3BY1iLhm
        VdDMh+hvMAq35EN9mruQO/tYIDRWgwoBwNtOo6wLtJwd/cqZBOw0kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T09:00:01Z"
  mac: ENC[AES256_GCM,data:S4qs+zrh3mxH6Y7zfGBGAUXnP+p7UH8cvlRqNg7BhHi9KDAckFgeAu+3Vp+ma7Sw7OseoitGRtmOnZUGLcAGzUBFfgPJta1F6QNSMXqkIqGC9atWTBxKb5g82QrEs92GBcTDek9YPP2SyfZeHLtkYrdpd/QVvITC39mrD2uYv/M=,iv:NsDNjh5RwawjhKkyPujfJzUtxxuOORujmyCDB3AEgC0=,tag:fQm8QGVSbq/Z9bmuD1Epcg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
