apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KBIJ3LlQEOdX8DxWFeS9TkykfitSIVN7nClNiwlefOfzkPH4BFl+lsSRUoJHtlnmRy38zvg46J3CfXDyGAa+IRukUm4Uhjptq/zwsnVSNKGACf2ZRzt0lIf220qmHSSkt/hq5i1SI2c4Mzc9BmWORQAS+7bZO1mWsVtB+9HD3FHevbuCoPan8roxuocDFTCw+DGJVvBX7TCsilvF1tbH0nLW5MIPX6H/fWV53E98yJDUijLf,iv:WP13UptpIIMWGKKasZWIiMSy/7q7VlMk01zmzkHtr/o=,tag:ZHGJvEg29OSTe2M0ToL2iw==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZkdIY2hTejFOWjNxaEE4
        MkZuUlB4YVhjZzV0WXArZ1VKRFhZT1V6dUZjCi80eXhWWmdFTmdvT1dNVTZjMmRa
        bnQraXV1VUx1Y2h5V3A3a1NjZEI1T2cKLS0tIFBPOG0rRzZVWUxlZmRXdmJxTlR6
        TkM2aUNQaGJwc3VBVkpJcUZoR1JiNHMKWOHR1drnzMivlH/lXEYrKn7RKdzfnN7T
        sh/sAlBDLZS1y3WcsbMj1YHGGSPLtVhNaCPEiG8FACmTEXA61UWKrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:44:10Z"
  mac: ENC[AES256_GCM,data:lDTW7jo9mFDcJDrEUG832d0hVx2MNKAazHLersUNuw9J42UODoqDXq++tDt6rSctGLD9LIOe2gvUbAOjKhIy5WehOKWuQfPLgEHBJUpQAAdo1F5FBP/rTi6dFaXgDslNz6obxwHeA1WklBf2E7f2FFz7CE39NP2HouwyK/3Klts=,iv:gzjLNahhD0QUIHrOq5Am95fbhW2lYdXV3cWIgAmTUfs=,tag:aCrJlkdlSfJ9esj2MzB/Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
