apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:aOyBu0lDU7cy+AHWzU4ARAx7rep5A10WOaevF6Gc4FZ4TcP7ULFQr9ly4RsFBc6QGIRZRJup/itlgYiIpRDrmJIqtV9m7og0UrF6PFrIxzzAEFeMD3wko8lV0ZOrzI5lrv3xKw2xfkjM6RJ3eEKDmfO6AmJ3Sw7r/CjjVV34lsqF49mwjaJNTUWgh3zOv+981peUArbAvek6dsvI+tuxRE3TiZVCfxs1r3GZX2Rbu7uvdvL6,iv:xg1p9gaI2qFnds1SSQoXviJLZyTPhqNZrpKgmit8oA4=,tag:yQv5pIkC8TrdVAejOj92NA==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYXpJL3h1aHpSQ1NVWHFD
        NzhQck5QYTA0TTZRY1lCay83ZGxOZnBjekg4Cm1vbjI0UU0yalVJQTJBaEt4NkZU
        SkJrZi9mY3FqMHBpczFuWHpiRDRQWmMKLS0tIHdRMHIrWHptNS9ieDVEbHUzNEFl
        U2o2U3NaTlphYXpVb3FoSnJPbEprNVkKUqmrAcIuY/5HtROYqmSMWTOj+NkydlzL
        9WhHTYPW/GaUb4c1dxYfRgbOIEzkIe/8u7HqRtCU27I72Vc7hTXsQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T17:09:33Z"
  mac: ENC[AES256_GCM,data:gWW9wDLmUkyt1PzJjw4gIDsICn1m83qweZ9CEzlM23VGMXpfvYcaS5XWCsQjDnc9qQlXNLZZoQOEMzyfi+8BPFoTtDQ3ghFRI99qyC+jTGeflOzN/RwUtqP6P/OWdVzBGeg+efNqDRfIjZVRNP0gFB+c8i7oTUr1A4xDyfvS6lw=,iv:CLQoyxBKAFl+tC90/p0ZjfDsoiYoVtf9XkwQihxBADk=,tag:qw5ibSNXEu5RPPVDhE3AHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
