apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:2qlMvkFE6nCucgZA1vzznO1zsD1iwQLDfhz7pUVg1WEENirt75sKDMU6idazrDFZhkrv98CTTo1FSDbCVBAOAOoBOSMR6QwYUKyrYQMOOWoHwNoxlWA8aiYVCq3jxkkBu/QitQKqcL/bH9r8o2xdboJWyUqxtowlfOIvrdk5umrPfdTTUocF8WjBh5tU6xIm7tQuT47IwCZ2AC3RTmJsSswRLJm0kJKFTBSnvDab6PM4Pybb,iv:aVuNibPbNvsUvOG4Eg2ICu4e/nWB2WYoU1y1+86dV/8=,tag:rb8JNuMWX2n8J/N8kEolDg==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSmxUVUlzOHhxS3ZzaDQ5
        a1RWd2pMeCtDbFg5V2l6UFgyWHkzTkR4TENBClE0cW1qTEtZNk1EZ0F5WGFPK0xE
        ZHhMalh3RzEzUDFTRS8vcE5QSy9halkKLS0tIEs5bVB2eXk2Uk9sNXNpQnl3QUdB
        NnppejY3MEFwd3QraVFBSFFsK0NHZk0Ktw1ht6vH50CagPlIoVwWhmURPW0yVGHs
        38pbl/9JujLEmJC88PVOyd82V9DSHgAfaK7oPbMPZXC/gnrCwFwUzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:51:47Z"
  mac: ENC[AES256_GCM,data:Vag5LL21vmnoXFp2XCisDIJZTbud2lJ1g6k2E4aCAhIiOhNJu93DS8l15PRop1hZX1mdOQPgOwlKzH0ivHuS25vh8NXCcFpuRnk3XbMx4LVjeG8CIfUagJR1HHJQ5ccA6LSE+MMZnlq8LPSj9WGK7kDxxJTksoYbChVFkGScTLU=,iv:4UI4cG05nWO5YqoUCGZFBNn+UcEYEKjIboQkw7of+BI=,tag:VBsoQ2i2sJ20WP9kgfIUCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
