apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:NQ+MqTvlDFU603X4GHjI3i+kdYrGKucn3fhWiM28AMaFWehTqLyB9OMUMIqcojHe8x/n8wjMdhxTX0Km4hyBLoquRmlA+1DauhwRbAYIXYBOkfZ65Flm2YGbKIecSKkMzm7/qkkn8uSv/D0yOoLC4m8UGcrF5ziRshptsL3e4UunEPF24s1gN6rXyh58Sf4HNHfIhBe777WZzqNkG19cG6MXi/h9Lu9JBucQNhFOmdi9ey9l,iv:ivwvkGmgkIC6hqCg3OWiknA+3erGIrFdOWmZIidS3FA=,tag:sTXaqynLyHhKFk0Ksxv08w==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cDEzSmdEUDNGRGdjU01W
        QitCZW5rLzFYam5sNWczU0NFVEswb3lEQlRzCmtKSW5uK3F1MzJkRTJ3SU0ybDJh
        Vk9pSzdON25LR2JrbmU5Wi9mWU56UUkKLS0tIDRPU3ZLSDdVQ2FrN0VFMUVDQzk1
        bG5XM01zR1p5UkIvY01rMDVUeHpTY0kKrxSnkTP3nY/+QVAQi5MgyiBXXzAh2MqV
        0+ZlKQF1k1kmg2GlLKjBZMwBmzkzlkrdVO3c53lXR6wfp+nUVt1MyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T20:03:36Z"
  mac: ENC[AES256_GCM,data:iHl5YqOOqYOlqE88IduKtmH2EClEq9ewl/mt2EOR8sXoLVq+H/21726Cd8JGnkqA1yFUl8EIx16qhLVMKW5/yaYY0nXAjAFilrnx9f6Hb4HaEfcPfGpKeANp5IA+O17+c2Ui6uHlnXjlQF/XjXNh4YNm+tT1FlK2kaRhv9T6ZlY=,iv:0w3h25/XM+FNqM563/C56NMYsdLXVoNi2E/WGYjeOj8=,tag:NowIJss2TvtRdkft1cJbnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
