apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:AaX3jdKvJt3j6zBFbgN2n8cbwC9mJQhP7WMZgMEkm1FYT5FMwqVzZw==,iv:kchjmHQOs4dKtLIYmHDvLp1MMV7iB7L9J3gNP+062gI=,tag:EBZlT7eihpqv6oNC85p0PQ==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOE1DUm9idGcwbDJCZTJm
        NGdweFFxVEJaWEpSTVh4Y1BYMFdsb1QxcVJ3CkpUNFkzbkF0WXlwU3FWaEFka3c2
        SGxuYWRiTWltaEhVSkI2aEFLbzhTTXMKLS0tIFRDZ0UvU2UveU12NzlHMjhHK3di
        S2tMVlY2eGFQNnp5VWlCYnZRZElrODAKn2JuiEuWR7S3RWtYXrF3IKokuyIALOFb
        276CFZtBcBLsBVGTAEs2c+WI8T0bjsePtJXMjxAftDx2c2bAVfXnGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T13:51:47Z"
  mac: ENC[AES256_GCM,data:ik9Yhv3jQ21r8OIUHmRAitXGhSBSVxTypAzY6ukuXsN9dWiCcIKCzme+tAp2Ur+p2fxaVXfzTmbH+Zz+KT+qhchtEEyQ99TUm3MyM7FJPbww7VE5vbtoJLaO4hp7K7CFmTmQnCDpI4Mcg7gIngm0DMm7DEgN9peTdXolbl0Epxs=,iv:mVSsNZdd6MTQSYH0bf0+2F9KNJwFESGhriir3+pGOrQ=,tag:0Om6LzHgRSZYKE8W+7OhzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
