apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1LYRmOnYq7/7tg7DWaQvt3Zh181yleSwOsQz3n/EJ4IXn5Sw4hTABw==,iv:bY7ZZvo80ekp6V9Ps40JmIcbdNwIbEYtvQchWx9ad18=,tag:tgyQHE4d8u0YnR1TFRkoKg==,type:str]
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNWUwOVZvYVRORW1ZT05T
        ejF5MnpqdjExcEt3QWJuOGwxTmRsRmVyNWlzCkZKYTRPREYxTnliSldOZWIwTXBl
        VW0vbGdXTGpIQWdSL2g1YVdRMzM0TzQKLS0tIG14MDZiUGI5SEVINlZ1M1ZuS0Rh
        VmRydktMbGI3QjlVOW1lTDBldzVUQVkKLuxH5r5W/n2IVKj1Q3vcT39qldJnDCxy
        l70w+Mb8VA0ionkmiG7el1WQAR6H7q/465CcdbCidG7BINUUD3dvZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T17:09:33Z"
  mac: ENC[AES256_GCM,data:Tbc4sedUqcCOJgUB8rhZDM7GSdI8zsQjOJdTI/Wtz5d9h/mIUnFx5KBE4bUx6cSXYDPG+ZjT1OQVrM//HfXia2qmTQ3s/3nLkk9aSEzXQSxmcJoOYZOlRo1xiJoIo4/mJ4NtsA0X54EgL+Y/ZAv+Dphb93eRax6UbCls5UxgdMQ=,iv:NxqYj0RxRG2SrhuJUSL8qfdXgD/AuY5QzHrmULHLfyM=,tag:txu5siRW3SUWHbHb+EXhRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
