---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/flux-alerts
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./blackbox-exporter/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./grafana/ks.yaml
  - ./kepler/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./victoria-logs/ks.yaml
