---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
spec:
  chartRef:
    kind: OCIRepository
    name: kepler
  interval: 1h
  values:
    config:
      log:
        level: info
    fullnameOverride: kepler
    daemonset:
      resources:
        limits:
          cpu: 3000m
          memory: 128Mi
        requests:
          cpu: 160m
          memory: 128Mi
    serviceMonitor:
      enabled: true
      interval: 10s
      scrapeTimeout: 15s
