---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opnsense-dns
spec:
  chartRef:
    kind: OCIRepository
    name: opnsense-dns
  interval: 15m
  values:
    fullnameOverride: *app
    domainFilters:
      - arita.moe
    extraArgs:
      - --ignore-ingress-tls-spec
      - --gateway-name=envoy-internal
    interval: 10m
    logLevel: &logLevel debug
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
          tag: pr-11@sha256:2827f2db25ef1acfc090313a3c4dce2be707ffe51fb9ceb1420ac6fd4498d130
          pullPolicy: Always
        env:
          - name: OPNSENSE_API_KEY
            valueFrom:
              secretKeyRef:
                name: &secret opnsense-dns-secret
                key: OPNSENSE_API_KEY
          - name: OPNSENSE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: *secret
                key: OPNSENSE_API_SECRET
          - name: OPNSENSE_HOST
            valueFrom:
              secretKeyRef:
                name: *secret
                key: OPNSENSE_HOST
          - name: OPNSENSE_SKIP_TLS_VERIFY
            value: "true"
          - name: LOG_LEVEL
            value: *logLevel
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
    resources:
      requests:
        cpu: 58m
        memory: 128Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    sources:
      - service
      - gateway-httproute
    triggerLoopOnEvent: true
    txtOwnerId: k8s-internal
    txtPrefix: k8s.
