apiVersion: v1
kind: Secret
metadata:
  name: opnsense-dns-secret
stringData:
  OPNSENSE_API_KEY: ENC[AES256_GCM,data:xeQEHR+oc9eFEmkfPBAZe2MB8/xptxVfuWsrM2mxUKW10OXGPI6LWgXHDzi28gc7Hb588dMPruwaMCJlfr1cozMGkHvQOGfcyoQIKuYlKI8=,iv:FZRAG8TLlZ3ISBxTMbwOI4yzUY/0yjfI9rd9OfzHulo=,tag:VaqFMdDYdUWZE9OMoOZpBQ==,type:str]
  OPNSENSE_API_SECRET: ENC[AES256_GCM,data:QW4Y4/fKlbxFrD6c0F4Y/z59Ze5mXLWUwpk8/asJPP0TLqesjmMy1tUQCNxyQ22iuHsYkJFzqVWuKKZgrZvFbhGxsCYjEK6tw/rhHvpeuzY=,iv:vtEE0gDwsZF9K+RaaOmk+Gpm2fcNHB3m/uNF/RovhK0=,tag:YLEAqoxpVPQSBjvWyTUAIw==,type:str]
  OPNSENSE_HOST: ENC[AES256_GCM,data:FrZXrr/EWO31RCIyjHC0KbjStA==,iv:WUyFlwtba0phukgDsAn9r2asoITMiDdeR240S0SCLCU=,tag:PsUYSnGmzkYaUzfn4Rw37g==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWktVWWJqQ3FpamhUcXBK
        ZkhzZzFyUkFMWlNQMjZtRmx6engyQ2VXSkFrCjVCdHg3ODg2T1dOQis2REl2SFdw
        S3RuQ1ltb1Qyd2FzTG4zUGoxM3JGOHcKLS0tIFlWS1ViN3NubDdSV0dDYUZIdklq
        OVRBcmdnQWRkRllsRFp5N0dOb2ZVYzQKkXxbaPTWXsziBgzf4O/gmtRS0jkQbkcf
        Rwi7HwrHJguelFaozbS+Y1EqU7PyyQuyoGcnBmAdG4ZBoTx3H6SYxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T22:11:33Z"
  mac: ENC[AES256_GCM,data:JeQ83DRmcWCHeu3fbNsbSKewwv58OY516pcABcAjbfjEqpOWRVrMye32vKWPVrpZXPR0O5NTrvsFoQwLtzbWv71Z0syIvO7HPL+y8L4hNEupZf8ZewJLyxAJ6PnIug9xiAH0z3FzAi7NJRcRWtJuatv0CfttF40iqpqB5sCeSkc=,iv:5Uc8J4Zm3xyNoPstVtm9d56K42Oy+ppOGmqMANmhlZI=,tag:JdtLCxKSrZcrIurxZVNDkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
