apiVersion: v1
kind: Secret
metadata:
  name: opnsense-dns-secret
stringData:
  OPNSENSE_API_KEY: ENC[AES256_GCM,data:wU1Di4AAjU0KsxiZvGk/Qqo3lZJ9ExDPjYibjfZ+SWx1mRB/LSpduLYt0IHzQgvxD26XCH6PbdsTh3ZyqJrR6V9mHDg7bKWnZupOOrgAlgY=,iv:TiD5VmM/70B8bk8FKyd1Qri+Q8VOno6bhZzQ1Iln+c0=,tag:DT9uvD6c7DXXNKXojud8eQ==,type:str]
  OPNSENSE_API_SECRET: ENC[AES256_GCM,data:0VygIUSttk3oSDY=,iv:ZWiI0Setp7tNHZHrDt/xy5GDFzltanjkfN+uLbLVKT4=,tag:NcCd1l8iFMN3z+R6frvBjw==,type:str]
  OPNSENSE_HOST: ENC[AES256_GCM,data:JLPf2qizE+zKSs6DP3IEUDsUNQ==,iv:mLxybDy/oz9mXLxNE4R4yaHL2vpPeCFoNHFs3fycbSI=,tag:+ZLqoup+i3Gh85RZwh7itg==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1cunrtvnawc3eanh9n87vvyvkqljsmsw3zl8ag2jklj7xlzcm058snqx90t
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSFNIMDBRMkkxdVNnMTZy
        OXAzOUx1Tmkydmllek04dDhOY0VpZjlOcW5VCkd0M1BFT01WaHlyMFRzZGhoeXNy
        clR2b1RhRGkzUjRWU0RJQnExazE1dnMKLS0tIDgvMFBWaW0yY29QYjFFYkhHajBo
        RkFPWGFkRmlac1NjeDRwZDI5Nmgzd2sKyM9FMGpsWo+Zm5bPCR3rqZF8YedIf1oP
        EcmZ6lqT3dPSMqy4fW758V4koeSVqUx1uDycgiyCIz9/mVvazn3/kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T21:52:53Z"
  mac: ENC[AES256_GCM,data:dzUmgnxs7TSAJC4bxHUBArtXXI4Psl5+2RIMQHVj44PRYtHrsNbz8T1heln72qiv5+oACMjh0zJRxU+SxX6Zikk+0dsVLZ28YWEfMhaMX5gOZU7xHhQln0RVPMT0ECK5YTVAH6PWmxEQIeEp2hdF1COE/LDQw1sTvTOHLDByShg=,iv:VEoI+aMdwav/gx9WQSJSzoIbDN4sSZ6ag0atfWWB+AE=,tag:+9t6mvJO+4GvnW/hdL+mRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
